Console.Write("Enter Attendee Name - ");
string attendee = Console.ReadLine() ?? "";
Console.Write("Enter Organization Name - ");
string org = Console.ReadLine() ?? "";
Console.Write("Enter Contact Email - ");
string contact = Console.ReadLine() ?? "";
Console.Write("Enter Access Level - ");
string access = Console.ReadLine() ?? "";
Console.WriteLine("+----------------------------------------+");
Console.WriteLine("|                APEX ENTERTAINMENT PASS |");
Console.WriteLine("|----------------------------------------|");
Console.WriteLine($"|  ATTENDEE     : {attendee.PadLeft(23)}|");
Console.WriteLine($"|  ORGANIZATION : {org.PadLeft(23)}|");
Console.WriteLine($"|  CONTACT      : {contact.PadLeft(23)}|");
Console.WriteLine($"|  ACCESS       : {access.PadLeft(23)}|");
Console.WriteLine($"|BCH SOFTWARE TERMINAL SYSTEM            |");
Console.WriteLine("+----------------------------------------+");
