Console.Write("Enter Attendee Name - ");
string attendee = Console.ReadLine() ?? "";
Console.Write("Enter Organization Name - ");
string org = Console.ReadLine() ?? "";
Console.Write("Enter Contact Email - ");
string contact = Console.ReadLine() ?? "";
Console.Write("Enter Access Level - ");
string access = Console.ReadLine() ?? "";
string name = ("BCH SOFTWARE TERMINAL SYSTEM");
Console.WriteLine("+----------------------------------------------------------------------------+");
Console.WriteLine("|APEX ENTERTAINMENT PASS                              APEX ENTERTAINMENT PASS|");
Console.WriteLine($"|  ATTENDEE     : {attendee.PadLeft(59)}|");
Console.WriteLine($"|  ORGANIZATION : {org.PadLeft(59)}|");
Console.WriteLine($"|  CONTACT      : {contact.PadLeft(59)}|");
Console.WriteLine($"|  ACCESS       : {access.PadLeft(59)}|");
Console.WriteLine($"|  ISSUER       : {name.PadLeft(59)}|");
Console.WriteLine("+----------------------------------------------------------------------------+");
